language: erlang

otp_release:
  - R16B03
  - 17.4
  - 18.3
  - 19.3
  - 20.0

script: rebar3 update && rebar3 eunit && rebar3 dialyzer && rebar3 coveralls send

cache:
  directories:
  - $HOME/.cache/rebar3/
