language: erlang

otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02

script: PATH=.:$PATH make update test dialyzer coveralls

install: wget https://github.com/erlang/rebar3/releases/download/3.1.0/rebar3 && chmod 755 rebar3

